# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11238bc20eeb3941b1b373fe19dcc4935f33f77ae8ab6a1a8320bd0382175d9b16bd437020d75a88631b7bbbe8ddca3fa6feba71d0b06571787b90e456857775

test:
  secret_key_base: d8b02d9d49c32e72d31b910556c1b941884cc6dd55e34444bc552afc9e1c2f30063d8bdafc4e498b77bb8b467d5a30496e1e3b9a426096644b95fe34164a3985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
